from .base import *

DEBUG = False
<<<<<<< HEAD
ALLOWED_HOSTS = ["43.200.89.250"]
=======
ALLOWED_HOSTS = ["13.209.235.183"]
>>>>>>> cb3a0b7fdb47fe48e69e74d83fb257c5f5824086

DATABASES = DATABASE
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = []

# # CORS 설정
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True
#
# CSRF_TRUSTED_ORIGINS = ["http://13.209.235.183"]
# CSRF_COOKIE_SECURE = False
# SESSION_COOKIE_SECURE = False
#
# # Cross-Origin-Opener-Policy 설정 제거
# SECURE_CROSS_ORIGIN_OPENER_POLICY = None
# SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = None
